### PR TITLE
build: update OT to 1.31.0

### PR DESCRIPTION
**Pull request by sdelamo**

### CODE REVIEW

**Comment by sdelamo** [comment]
@timyates do you know how to work around the `checkbox` failure?

**Comment by timyates** [comment]
It's because some of the libs are still on 1.30.1, and these are pulling in 1.30.1 BOMs, but we updated the dependency exclusions to be 1.31.0

**Review by sdelamo — COMMENTED** [review]
> It's because some of the libs are still on 1.30.1, and these are pulling in 1.30.1 BOMs, but we updated the dependency exclusions to be 1.31.0

will this mean we will expose both BOMs 1.31.0 and 1.30.0?

**Comment by timyates** [comment]
I *think* the answer is yes...

So I believe Gradle will make a sensible decision and pick the latest, but Maven will pick the first it sees...

I hope `opentelemetry-instrumentation:1.30` works well with `opentelemetry:1.31`

**Pull request merged**
