### PR TITLE
Refactored micronaut tracing-opentelemetry-kafka.

### PR DESCRIPTION
**Pull request by altro3**
Added some important features and fixed bugs:

1. Wrappers for consumers and producers were created twice - fixed
2. Added filter messages to trace
3. Added filter topics to trace
4. Added ability to disable span attributes prefix
5. Added ability to customize span attributes prefix
6. Added default TracingConsumerInterceptor and TracingProducerInterceptor to connect them to kafka client with same functionality

### CODE REVIEW

**Comment by altro3** [comment]
@n0tl3ss @graemerocher previous integration was bad and with bugs :-). But, I think only I used this library in prodcuction and saw all the problems of the previous implementation.

Now I have added all the necessary tools for working with tracing, which were missing in opentelemetry-kafka . I had to abandon this library and modify it so that it was possible to filter messages and topics, as well as customize prefixes for span attributes

**Comment by altro3** [comment]
@graemerocher yeah, many codestyle errors. Fixed

**Comment by altro3** [comment]
@graemerocher I analyzed theirs last version code and now I can say that we don't need to fork `opentelemetry-kafka-clients-common` module and can use official library, but I want to replace theirs extra-small module `opentelemetry-kafka-clients-2.6` (only 4 classes), because we will not be able to integrate with them without redefining these 4 classes. Therefore, it makes no sense to include this library at all, because. she just doesn't fit us.

So let's update micronaut-tracing to the latest version of opentelemetry and after that I will change this PR so that it does not fork classes from the opentelemetry-kafka-clients-common library.

Please, look here #271

**Comment by altro3** [comment]
@dstepanov +

Don't need it inside micronaut-kafka anymore

**Comment by altro3** [comment]
@graemerocher merged all changes from other branch and removed all classes from kafka-common library

**Comment by graemerocher** [comment]
good point, deleted 4.7.x so this now need to target 4.6.x

**Pull request closed without merging**
